#' Extract tag colours from a dataframe to create a colour scale
#'
#' @param df A dataframe generated by download_game_data()
#'
#' @return A character vector for passing to scale_colour_manual()
#' @export
extract_colours <- function(df) {
  colours <- df |>
    select(tag, hex, session) |>
    group_by(tag) |>
    dplyr::filter(session == max(session)) |>
    select(tag, hex) |>
    tibble::deframe()
  
  return(colours)
}

#' Create a dataframe of labels for the end of the line graph
#'
#' @param df A dataframe generated by download_game_data()
#'
#' @return A dataframe for passing to the labels argument of geom_text()
#' @export
clean_labels <- function(df) {
  label_df <- df |> 
    mutate(label = ifelse(session == max(session), tag, NA))
  return(label_df)
}


#' Plot the session history for a metric
#'
#' @param df 
#' @param metric
#' @param metric_string 
#' @param file_path
#'
#' @return A saved plot of the per-tag session history for that metric
#' @export
plot_session_history <- function(df, metric, metric_string, file_path) {
  ggplot(df, aes(x = session, y = {{ metric }}, colour = tag, group = tag)) +
    geom_line(linewidth = 0.7) +
    geom_point() +
    geom_text_repel(
      data = clean_labels(df),
      aes(label = label), 
      nudge_x = 0.1, 
      na.rm = TRUE, 
      hjust = 0, 
      size = 2,
      min.segment.length = 0, 
      direction = "y", 
      force = 0.01, 
      force_pull = 10
    ) +
    scale_x_discrete(expand = expansion(mult = c(0, 0), add = c(0.1, 0.4))) +
    scale_colour_manual(values = extract_colours(df)) +
    theme_bw() +
    theme(legend.position = "none") +
    labs(
      x = "Session",
      y = metric_string
    ) +
    scale_y_continuous(label=scales::comma)
  ggsave(filename = paste0(file_path, metric_string, ".png"))
}