#' Remove unwanted tags from the data
#'
#' @param df A dataframe generated by download_game_data()
#' @param tag_removal_df A dataframe with two columns: tag and remove_until
#'
#' @return A dataframe
#' @export
remove_tags <- function(df, tag_removal_df) {
  df_filtered <- df |> 
    dplyr::left_join(tag_removal, by = "tag") |> 
    dplyr::filter(
      session >= remove_until |
      is.na(remove_until)
    )
  return(df_filtered)
}


#' Update data to reflect tag switches
#'
#' @param df A dataframe generated by download_game_data()
#' @param tag_switch_df A dataframe with two columns: tag and new_tag
#'
#' @return A dataframe
#' @export
switch_tags <- function(df, tag_switch_df) {
  df_filtered <- df |> 
    dplyr::left_join(tag_switch_df, by = "tag") |> 
    dplyr::mutate(tag = ifelse(is.na(new_tag), tag, new_tag))
  return(df_filtered)
}